/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VisualService } from "../visual.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VisualCreateInput } from "./VisualCreateInput";
import { Visual } from "./Visual";
import { VisualFindManyArgs } from "./VisualFindManyArgs";
import { VisualWhereUniqueInput } from "./VisualWhereUniqueInput";
import { VisualUpdateInput } from "./VisualUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VisualControllerBase {
  constructor(
    protected readonly service: VisualService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Visual })
  @nestAccessControl.UseRoles({
    resource: "Visual",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createVisual(@common.Body() data: VisualCreateInput): Promise<Visual> {
    return await this.service.createVisual({
      data: data,
      select: {
        createdAt: true,
        id: true,
        sourceUrl: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Visual] })
  @ApiNestedQuery(VisualFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Visual",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async visuals(@common.Req() request: Request): Promise<Visual[]> {
    const args = plainToClass(VisualFindManyArgs, request.query);
    return this.service.visuals({
      ...args,
      select: {
        createdAt: true,
        id: true,
        sourceUrl: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Visual })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Visual",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async visual(
    @common.Param() params: VisualWhereUniqueInput
  ): Promise<Visual | null> {
    const result = await this.service.visual({
      where: params,
      select: {
        createdAt: true,
        id: true,
        sourceUrl: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Visual })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Visual",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateVisual(
    @common.Param() params: VisualWhereUniqueInput,
    @common.Body() data: VisualUpdateInput
  ): Promise<Visual | null> {
    try {
      return await this.service.updateVisual({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          sourceUrl: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Visual })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Visual",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVisual(
    @common.Param() params: VisualWhereUniqueInput
  ): Promise<Visual | null> {
    try {
      return await this.service.deleteVisual({
        where: params,
        select: {
          createdAt: true,
          id: true,
          sourceUrl: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
