/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VoiceOverService } from "../voiceOver.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VoiceOverCreateInput } from "./VoiceOverCreateInput";
import { VoiceOver } from "./VoiceOver";
import { VoiceOverFindManyArgs } from "./VoiceOverFindManyArgs";
import { VoiceOverWhereUniqueInput } from "./VoiceOverWhereUniqueInput";
import { VoiceOverUpdateInput } from "./VoiceOverUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VoiceOverControllerBase {
  constructor(
    protected readonly service: VoiceOverService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: VoiceOver })
  @nestAccessControl.UseRoles({
    resource: "VoiceOver",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createVoiceOver(
    @common.Body() data: VoiceOverCreateInput
  ): Promise<VoiceOver> {
    return await this.service.createVoiceOver({
      data: data,
      select: {
        createdAt: true,
        id: true,
        language: true,
        sourceUrl: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [VoiceOver] })
  @ApiNestedQuery(VoiceOverFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "VoiceOver",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async voiceOvers(@common.Req() request: Request): Promise<VoiceOver[]> {
    const args = plainToClass(VoiceOverFindManyArgs, request.query);
    return this.service.voiceOvers({
      ...args,
      select: {
        createdAt: true,
        id: true,
        language: true,
        sourceUrl: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: VoiceOver })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VoiceOver",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async voiceOver(
    @common.Param() params: VoiceOverWhereUniqueInput
  ): Promise<VoiceOver | null> {
    const result = await this.service.voiceOver({
      where: params,
      select: {
        createdAt: true,
        id: true,
        language: true,
        sourceUrl: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: VoiceOver })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VoiceOver",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateVoiceOver(
    @common.Param() params: VoiceOverWhereUniqueInput,
    @common.Body() data: VoiceOverUpdateInput
  ): Promise<VoiceOver | null> {
    try {
      return await this.service.updateVoiceOver({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          language: true,
          sourceUrl: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: VoiceOver })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VoiceOver",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVoiceOver(
    @common.Param() params: VoiceOverWhereUniqueInput
  ): Promise<VoiceOver | null> {
    try {
      return await this.service.deleteVoiceOver({
        where: params,
        select: {
          createdAt: true,
          id: true,
          language: true,
          sourceUrl: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
