/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumCampaignAspectRatio } from "./EnumCampaignAspectRatio";
import {
  IsEnum,
  IsOptional,
  IsBoolean,
  IsString,
  IsDate,
  ValidateNested,
} from "class-validator";
import { EnumCampaignCampaignLanguage } from "./EnumCampaignCampaignLanguage";
import { EnumCampaignCampaignNiche } from "./EnumCampaignCampaignNiche";
import { EnumCampaignCampaignVoice } from "./EnumCampaignCampaignVoice";
import { Type } from "class-transformer";
import { EnumCampaignLanguage } from "./EnumCampaignLanguage";
import { EnumCampaignNiche } from "./EnumCampaignNiche";
import { Project } from "../../project/base/Project";
import { EnumCampaignSocialAccounts } from "./EnumCampaignSocialAccounts";
import { EnumCampaignSocialChannels } from "./EnumCampaignSocialChannels";
import { EnumCampaignVideoAspectRatio } from "./EnumCampaignVideoAspectRatio";
import { EnumCampaignVideoLength } from "./EnumCampaignVideoLength";
import { EnumCampaignVideoLengthDuration } from "./EnumCampaignVideoLengthDuration";
import { EnumCampaignVoice } from "./EnumCampaignVoice";

@ObjectType()
class Campaign {
  @ApiProperty({
    required: false,
    enum: EnumCampaignAspectRatio,
  })
  @IsEnum(EnumCampaignAspectRatio)
  @IsOptional()
  @Field(() => EnumCampaignAspectRatio, {
    nullable: true,
  })
  aspectRatio?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  backgroundMusicIncluded!: boolean | null;

  @ApiProperty({
    required: false,
    enum: EnumCampaignCampaignLanguage,
  })
  @IsEnum(EnumCampaignCampaignLanguage)
  @IsOptional()
  @Field(() => EnumCampaignCampaignLanguage, {
    nullable: true,
  })
  campaignLanguage?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  campaignName!: string | null;

  @ApiProperty({
    required: false,
    enum: EnumCampaignCampaignNiche,
  })
  @IsEnum(EnumCampaignCampaignNiche)
  @IsOptional()
  @Field(() => EnumCampaignCampaignNiche, {
    nullable: true,
  })
  campaignNiche?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  campaignTone!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  campaignTopic!: string | null;

  @ApiProperty({
    required: false,
    enum: EnumCampaignCampaignVoice,
  })
  @IsEnum(EnumCampaignCampaignVoice)
  @IsOptional()
  @Field(() => EnumCampaignCampaignVoice, {
    nullable: true,
  })
  campaignVoice?: "Option1" | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  includeBackgroundMusic!: boolean | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  includeSoundEffects!: boolean | null;

  @ApiProperty({
    required: false,
    enum: EnumCampaignLanguage,
  })
  @IsEnum(EnumCampaignLanguage)
  @IsOptional()
  @Field(() => EnumCampaignLanguage, {
    nullable: true,
  })
  language?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name!: string | null;

  @ApiProperty({
    required: false,
    enum: EnumCampaignNiche,
  })
  @IsEnum(EnumCampaignNiche)
  @IsOptional()
  @Field(() => EnumCampaignNiche, {
    nullable: true,
  })
  niche?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => [Project],
  })
  @ValidateNested()
  @Type(() => Project)
  @IsOptional()
  projects?: Array<Project>;

  @ApiProperty({
    required: false,
    enum: EnumCampaignSocialAccounts,
    isArray: true,
  })
  @IsEnum(EnumCampaignSocialAccounts, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumCampaignSocialAccounts], {
    nullable: true,
  })
  socialAccounts?: Array<"Option1">;

  @ApiProperty({
    required: false,
    enum: EnumCampaignSocialChannels,
    isArray: true,
  })
  @IsEnum(EnumCampaignSocialChannels, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumCampaignSocialChannels], {
    nullable: true,
  })
  socialChannels?: Array<"Option1">;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  soundEffectsIncluded!: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  tone!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  topic!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    enum: EnumCampaignVideoAspectRatio,
  })
  @IsEnum(EnumCampaignVideoAspectRatio)
  @IsOptional()
  @Field(() => EnumCampaignVideoAspectRatio, {
    nullable: true,
  })
  videoAspectRatio?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumCampaignVideoLength,
  })
  @IsEnum(EnumCampaignVideoLength)
  @IsOptional()
  @Field(() => EnumCampaignVideoLength, {
    nullable: true,
  })
  videoLength?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumCampaignVideoLengthDuration,
  })
  @IsEnum(EnumCampaignVideoLengthDuration)
  @IsOptional()
  @Field(() => EnumCampaignVideoLengthDuration, {
    nullable: true,
  })
  videoLengthDuration?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumCampaignVoice,
  })
  @IsEnum(EnumCampaignVoice)
  @IsOptional()
  @Field(() => EnumCampaignVoice, {
    nullable: true,
  })
  voice?: "Option1" | null;
}

export { Campaign as Campaign };
