/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumCampaignAspectRatio } from "./EnumCampaignAspectRatio";
import { IsEnum, IsOptional, ValidateNested } from "class-validator";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { Type } from "class-transformer";
import { EnumCampaignCampaignLanguage } from "./EnumCampaignCampaignLanguage";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { EnumCampaignCampaignNiche } from "./EnumCampaignCampaignNiche";
import { EnumCampaignCampaignVoice } from "./EnumCampaignCampaignVoice";
import { StringFilter } from "../../util/StringFilter";
import { EnumCampaignLanguage } from "./EnumCampaignLanguage";
import { EnumCampaignNiche } from "./EnumCampaignNiche";
import { ProjectListRelationFilter } from "../../project/base/ProjectListRelationFilter";
import { EnumCampaignVideoAspectRatio } from "./EnumCampaignVideoAspectRatio";
import { EnumCampaignVideoLength } from "./EnumCampaignVideoLength";
import { EnumCampaignVideoLengthDuration } from "./EnumCampaignVideoLengthDuration";
import { EnumCampaignVoice } from "./EnumCampaignVoice";

@InputType()
class CampaignWhereInput {
  @ApiProperty({
    required: false,
    enum: EnumCampaignAspectRatio,
  })
  @IsEnum(EnumCampaignAspectRatio)
  @IsOptional()
  @Field(() => EnumCampaignAspectRatio, {
    nullable: true,
  })
  aspectRatio?: "Option1";

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  backgroundMusicIncluded?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumCampaignCampaignLanguage,
  })
  @IsEnum(EnumCampaignCampaignLanguage)
  @IsOptional()
  @Field(() => EnumCampaignCampaignLanguage, {
    nullable: true,
  })
  campaignLanguage?: "Option1";

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  campaignName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumCampaignCampaignNiche,
  })
  @IsEnum(EnumCampaignCampaignNiche)
  @IsOptional()
  @Field(() => EnumCampaignCampaignNiche, {
    nullable: true,
  })
  campaignNiche?: "Option1";

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  campaignTone?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  campaignTopic?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumCampaignCampaignVoice,
  })
  @IsEnum(EnumCampaignCampaignVoice)
  @IsOptional()
  @Field(() => EnumCampaignCampaignVoice, {
    nullable: true,
  })
  campaignVoice?: "Option1";

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  includeBackgroundMusic?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  includeSoundEffects?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumCampaignLanguage,
  })
  @IsEnum(EnumCampaignLanguage)
  @IsOptional()
  @Field(() => EnumCampaignLanguage, {
    nullable: true,
  })
  language?: "Option1";

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumCampaignNiche,
  })
  @IsEnum(EnumCampaignNiche)
  @IsOptional()
  @Field(() => EnumCampaignNiche, {
    nullable: true,
  })
  niche?: "Option1";

  @ApiProperty({
    required: false,
    type: () => ProjectListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ProjectListRelationFilter)
  @IsOptional()
  @Field(() => ProjectListRelationFilter, {
    nullable: true,
  })
  projects?: ProjectListRelationFilter;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  soundEffectsIncluded?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  tone?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  topic?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumCampaignVideoAspectRatio,
  })
  @IsEnum(EnumCampaignVideoAspectRatio)
  @IsOptional()
  @Field(() => EnumCampaignVideoAspectRatio, {
    nullable: true,
  })
  videoAspectRatio?: "Option1";

  @ApiProperty({
    required: false,
    enum: EnumCampaignVideoLength,
  })
  @IsEnum(EnumCampaignVideoLength)
  @IsOptional()
  @Field(() => EnumCampaignVideoLength, {
    nullable: true,
  })
  videoLength?: "Option1";

  @ApiProperty({
    required: false,
    enum: EnumCampaignVideoLengthDuration,
  })
  @IsEnum(EnumCampaignVideoLengthDuration)
  @IsOptional()
  @Field(() => EnumCampaignVideoLengthDuration, {
    nullable: true,
  })
  videoLengthDuration?: "Option1";

  @ApiProperty({
    required: false,
    enum: EnumCampaignVoice,
  })
  @IsEnum(EnumCampaignVoice)
  @IsOptional()
  @Field(() => EnumCampaignVoice, {
    nullable: true,
  })
  voice?: "Option1";
}

export { CampaignWhereInput as CampaignWhereInput };
