/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SoundEffectService } from "../soundEffect.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SoundEffectCreateInput } from "./SoundEffectCreateInput";
import { SoundEffect } from "./SoundEffect";
import { SoundEffectFindManyArgs } from "./SoundEffectFindManyArgs";
import { SoundEffectWhereUniqueInput } from "./SoundEffectWhereUniqueInput";
import { SoundEffectUpdateInput } from "./SoundEffectUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SoundEffectControllerBase {
  constructor(
    protected readonly service: SoundEffectService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SoundEffect })
  @nestAccessControl.UseRoles({
    resource: "SoundEffect",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSoundEffect(
    @common.Body() data: SoundEffectCreateInput
  ): Promise<SoundEffect> {
    return await this.service.createSoundEffect({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        sourceUrl: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SoundEffect] })
  @ApiNestedQuery(SoundEffectFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SoundEffect",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async soundEffects(@common.Req() request: Request): Promise<SoundEffect[]> {
    const args = plainToClass(SoundEffectFindManyArgs, request.query);
    return this.service.soundEffects({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        sourceUrl: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SoundEffect })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SoundEffect",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async soundEffect(
    @common.Param() params: SoundEffectWhereUniqueInput
  ): Promise<SoundEffect | null> {
    const result = await this.service.soundEffect({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        sourceUrl: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SoundEffect })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SoundEffect",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSoundEffect(
    @common.Param() params: SoundEffectWhereUniqueInput,
    @common.Body() data: SoundEffectUpdateInput
  ): Promise<SoundEffect | null> {
    try {
      return await this.service.updateSoundEffect({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          sourceUrl: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SoundEffect })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SoundEffect",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSoundEffect(
    @common.Param() params: SoundEffectWhereUniqueInput
  ): Promise<SoundEffect | null> {
    try {
      return await this.service.deleteSoundEffect({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          sourceUrl: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
